// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.3
// source: quant.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QuantClient is the client API for Quant service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuantClient interface {
	Request(ctx context.Context, in *QuantRequest, opts ...grpc.CallOption) (*QuantResult, error)
}

type quantClient struct {
	cc grpc.ClientConnInterface
}

func NewQuantClient(cc grpc.ClientConnInterface) QuantClient {
	return &quantClient{cc}
}

func (c *quantClient) Request(ctx context.Context, in *QuantRequest, opts ...grpc.CallOption) (*QuantResult, error) {
	out := new(QuantResult)
	err := c.cc.Invoke(ctx, "/proto.Quant/Request", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuantServer is the server API for Quant service.
// All implementations must embed UnimplementedQuantServer
// for forward compatibility
type QuantServer interface {
	Request(context.Context, *QuantRequest) (*QuantResult, error)
	mustEmbedUnimplementedQuantServer()
}

// UnimplementedQuantServer must be embedded to have forward compatible implementations.
type UnimplementedQuantServer struct {
}

func (UnimplementedQuantServer) Request(context.Context, *QuantRequest) (*QuantResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedQuantServer) mustEmbedUnimplementedQuantServer() {}

// UnsafeQuantServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuantServer will
// result in compilation errors.
type UnsafeQuantServer interface {
	mustEmbedUnimplementedQuantServer()
}

func RegisterQuantServer(s grpc.ServiceRegistrar, srv QuantServer) {
	s.RegisterService(&Quant_ServiceDesc, srv)
}

func _Quant_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Quant/Request",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantServer).Request(ctx, req.(*QuantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Quant_ServiceDesc is the grpc.ServiceDesc for Quant service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Quant_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Quant",
	HandlerType: (*QuantServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _Quant_Request_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quant.proto",
}
