# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import quant_pb2 as quant__pb2


class QuantStub(object):
    """데이터를 계산하기 위한 gRPC 서비스
    Client: Golang
    Server: Python
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Request = channel.unary_unary(
                '/proto.Quant/Request',
                request_serializer=quant__pb2.QuantRequest.SerializeToString,
                response_deserializer=quant__pb2.QuantResult.FromString,
                )


class QuantServicer(object):
    """데이터를 계산하기 위한 gRPC 서비스
    Client: Golang
    Server: Python
    """

    def Request(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuantServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Request': grpc.unary_unary_rpc_method_handler(
                    servicer.Request,
                    request_deserializer=quant__pb2.QuantRequest.FromString,
                    response_serializer=quant__pb2.QuantResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.Quant', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Quant(object):
    """데이터를 계산하기 위한 gRPC 서비스
    Client: Golang
    Server: Python
    """

    @staticmethod
    def Request(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Quant/Request',
            quant__pb2.QuantRequest.SerializeToString,
            quant__pb2.QuantResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
